language: c

#sudo: false

#cache:
#    directories:
#        - libs

branches:
    only:
        - master
        - commit

compiler: clang
        
before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -y git make python gcc g++ pkg-config libz-dev libglib2.0-dev dh-autoreconf libc6-dev-i386 wget unzip llvm libncurses5-dev clang
    - make prepare
    - if [ "$CC" == "clang" ]; then export CXX="clang++"; fi
    - make examples

script:
    - make all

after_script:
    - ./packer examples/opti
    - ./packer -t 48c7c034120000c3 examples/opti
