language: c

#sudo: false

#cache:
#    directories:
#        - libs

branches:
    only:
        - master
        - commit

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "nApk4WBMAcST8uW4BmlaOtT/6oV1FFgWmu5JDdWyQj1H4LAQIvWa4NtNw/7VrBp3JJlgQVDDNZL8UyqyzxCsZG6JewP+HFyY4rOxrLDraZDJHB8Uw1q8SLv4phgkm1lHyaBhO59kBIMEHtLrFJHPHsry1N0TGtGk/avqPSGr9Ic="

addons:
  coverity_scan:
    project:
      name: "awailly/nrop"
      description: "Build submitted via Travis CI"
    notification_email: aurelien.wailly+coverity@gmail.com
#    build_command_prepend: "make prepare"
    build_command:   "make all"
    branch_pattern: commit

notifications:
    irc: "chat.freenode.net#nrop"

compiler: clang
        
before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -y git make python gcc g++ pkg-config libz-dev libglib2.0-dev dh-autoreconf libc6-dev-i386 wget unzip llvm libncurses5-dev clang nasm
    - if [ "$CC" == "clang" ]; then export CXX="clang++"; fi
    - make prepare
    - cd libs/z3/build && sudo make install 
    - cd ../../capstone && ./make.sh && sudo ./make.sh install && cd ../..
    - make examples

script:
    - make all

after_script:
    - ./packer examples/opti
    - ./packer -t 48c7c034120000c3 examples/opti
    - ./packer -t 4889d8c3 examples/opti
